service: my-express-application

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

custom:
  serverless-offline:
    lambdaPort: 4000
    httpPort: 6000
plugins:
  - serverless-offline
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: hello-world
          method: get
          cors: true
      - http:
          path: payments
          method: post
          cors: true
